### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by politas** [cerebrate/NavBallsToYou#1]
Just wondering what this mod does that [NavBallUpDefault](https://github.com/BrianErikson/KSP/tree/master/HUDTweaks/NavballUpDefault) doesn't.

**Comment by cerebrate** [comment]
Absolutely buggerall, except being available before NavBallUpDefault was updated. Like I said in the forum thread, I was a tad impatient.

(Well, and there's a more elegant way to do the job that NBUD doesn't use because it's a direct port of the 1.0 way to 1.1, but that's not anything a user would care about.)

**Comment by politas** [comment]
Oh, so it was NavBallUpDefault you were duplicating for KSP1.1? I thought maybe there was another mod doing the same thing. Would you say your way of doing it is an improvement over NavBallUpDefault's way? If so, I'm happy to add it to CKAN.

**Comment by politas** [comment]
As in, lower memory/processor footprint?

**Comment by politas** [comment]
(Sorry it's taken so long, by the way. The automated submission process broke some time ago, and I'm working through the backlog)

**Comment by cerebrate** [comment]
@politas 

Yeah - well, actually, I was duping an older mod I used to use that did the same thing, MapShowNavBall, but it comes to the same thing.

As for improvement - technically, it is: NavBallUpDefault runs every frame to check if you've switched into map mode, whereas NBTY only runs when you actually do switch, so it uses less processor time overall. (Although it's not like NBTY uses a lot, and I'd be surprised if anyone could tell the difference on a machine powerful enough to run KSP at all, hence what I said earlier.)

For myself, I'd be happy to see it on CKAN!

Thanks,

-c
